<a href="https://colab.research.google.com/github/yosshi18/ejercicios.numpy/blob/main/array_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, libreria de ciencia de datos **




In [1]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [2]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [3]:
array_id

array([10, 20, 30])

ARRAY DE 2 DIMENSIONES

In [4]:
array_2d=np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 *DIMESIONES*

In [11]:
array_3d=np.array([(10,20,30),(40,50,60),(30,70,80)],dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [30., 70., 80.]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS


In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON 2 DIMENSIONES DE 4 FILAS Y 5 COLUMNAS

In [17]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [20]:
np.arange (11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [29]:
np.arange (15,30,2+1/7)

array([15.        , 17.14285714, 19.28571429, 21.42857143, 23.57142857,
       25.71428571, 27.85714286])

ARRAY CON INTERVALOS Y DIVICIONES

In [30]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [31]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY CON MATRIZ IDENTIDAD Y DIAGONAL DE UNOS

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

VALORES ALEATORIOS  DE 0 Y 1

In [62]:
np.random.random((6,6))

array([[0.0191804 , 0.36036897, 0.14205824, 0.19217828, 0.74363683,
        0.78460146],
       [0.01736379, 0.31334349, 0.48101529, 0.40662203, 0.81369269,
        0.03857579],
       [0.83803743, 0.74826635, 0.15801513, 0.93974449, 0.17886446,
        0.22624549],
       [0.46456301, 0.68121733, 0.51234436, 0.38209031, 0.59563035,
        0.79247069],
       [0.35437144, 0.25638796, 0.7321086 , 0.73297641, 0.22870476,
        0.27238585],
       [0.47384252, 0.52347548, 0.83042542, 0.88077792, 0.31546618,
        0.74432031]])

ARRAY PARA NUMEROS VACIOS DE 4*3

In [63]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])