<a href="https://colab.research.google.com/github/yosshi18/ejercicios.numpy/blob/main/mates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.int64

numpy.int64

In [2]:
#decimales flotantes
np.float64

numpy.float64

In [3]:
#numeros complejos cariables compleja
np.complex64

numpy.complex64

In [8]:
#boleanos
np.bool_

numpy.bool

In [ ]:
#objetos
np.object_

In [10]:
#cadena de texto
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [11]:
#FORMATOS Bytes
np.bytes_

numpy.bytes_

PROPIEDADES Y CARACTERISTICAS  DE ENTORNOS

In [13]:
array_3d=np.array([(10,20,30),(40,50,60),(30,70,80)],dtype=float)
array_3d



array([[10., 20., 30.],
       [40., 50., 60.],
       [30., 70., 80.]])

In [14]:
array_3d.shape

(3, 3)

In [19]:
#longuitud de datos
len(array_3d)

3

In [20]:
#numero de dimensiones
array_3d.ndim

2

In [21]:
array_5d=np.array([(10,20,30),(40,50,60),(30,70,80),(89,52,46),(78,12,36)],dtype=float)
array_5d

array([[10., 20., 30.],
       [40., 50., 60.],
       [30., 70., 80.],
       [89., 52., 46.],
       [78., 12., 36.]])

In [25]:
array_5d=np.array([(10,20,30),(40,50,60),(30,70,80),(89,52,46),(78,12,36)],dtype=float)
array_5d

array([[10., 20., 30.],
       [40., 50., 60.],
       [30., 70., 80.],
       [89., 52., 46.],
       [78., 12., 36.]])

In [27]:
import numpy as np


arreglo_5d = np.zeros((2, 2, 2, 2, 2))



display(arreglo_5d)


display(arreglo_5d.ndim)

display(arreglo_5d.shape)

array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]]])

5

(2, 2, 2, 2, 2)

In [29]:
array_5d = np.random.rand(6,6,7,8)

In [35]:
array_3d.dtype


dtype('float64')

In [36]:
array_3d.dtype.name

'float64'

In [37]:
#convertir de un tipoa  otro tipo de dato
array_3d.astype(int)

array([[10, 20, 30],
       [40, 50, 60],
       [30, 70, 80]])

In [42]:
array_3d.astype(int)

array([[10, 20, 30],
       [40, 50, 60],
       [30, 70, 80]])

OPERADORES MATEMATICOS

In [43]:
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [30., 70., 80.]])

In [51]:
array3=np.random.random((4,4))
array3

array([[0.46848144, 0.81343551, 0.55998126, 0.84200354],
       [0.86466266, 0.47659333, 0.63932388, 0.75179876],
       [0.62470344, 0.43957152, 0.03317467, 0.438149  ],
       [0.32883369, 0.43400341, 0.13171822, 0.98311087]])

In [48]:
array2=np.random.random((4,4))
array2

array([[0.86953582, 0.02916177, 0.63529831, 0.17814719],
       [0.99945347, 0.64660698, 0.7967091 , 0.0067894 ],
       [0.17510724, 0.03607855, 0.41212565, 0.58827614],
       [0.72193852, 0.10897969, 0.07819695, 0.49604571]])

In [50]:
array1=np.random.random(( 4,4))
array1

array([[0.20376554, 0.0537797 , 0.23162957, 0.0998859 ],
       [0.88381378, 0.56830077, 0.17808929, 0.22501121],
       [0.20646036, 0.50949922, 0.86913172, 0.11849326],
       [0.18831146, 0.96830078, 0.65961288, 0.77473432]])

In [52]:
#sumas
array4=array1+array2+array3
array4

array([[1.5417828 , 0.89637697, 1.42690914, 1.12003663],
       [2.7479299 , 1.69150109, 1.61412227, 0.98359938],
       [1.00627104, 0.98514928, 1.31443204, 1.14491841],
       [1.23908367, 1.51128388, 0.86952805, 2.2538909 ]])

In [53]:
#OTRA FORMA DE SUMA
np.add(array1,array2,array3)

array([[1.07330135, 0.08294146, 0.86692788, 0.27803309],
       [1.88326724, 1.21490776, 0.97479839, 0.23180062],
       [0.3815676 , 0.54557777, 1.28125737, 0.7067694 ],
       [0.91024999, 1.07728047, 0.73780983, 1.27078003]])

In [54]:
#OTRA FORMA   de suma
array4=np.add(array1,array2,array3)
array4

array([[1.07330135, 0.08294146, 0.86692788, 0.27803309],
       [1.88326724, 1.21490776, 0.97479839, 0.23180062],
       [0.3815676 , 0.54557777, 1.28125737, 0.7067694 ],
       [0.91024999, 1.07728047, 0.73780983, 1.27078003]])

In [62]:
#multiplicacion
array4=np.multiply(array1,array2,array3)
array4

array([[0.17718143, 0.00156831, 0.14715387, 0.01779439],
       [0.88333074, 0.36746725, 0.14188536, 0.00152769],
       [0.0361527 , 0.01838199, 0.35819147, 0.06970676],
       [0.1359493 , 0.10552512, 0.05157972, 0.38430364]])

In [63]:
#resta versiona nterior
array4=np.subtract(array1,array2,array3)
array4

array([[-0.66577028,  0.02461793, -0.40366873, -0.07826129],
       [-0.11563969, -0.07830621, -0.6186198 ,  0.21822181],
       [ 0.03135312,  0.47342067,  0.45700607, -0.46978287],
       [-0.53362706,  0.85932109,  0.58141593,  0.27868861]])

In [64]:
#dividir
array4=np.divide(array1,array2,array3)
array4

array([[ 0.23433829,  1.84418513,  0.3645997 ,  0.56069311],
       [ 0.88429707,  0.87889674,  0.22353114, 33.14152448],
       [ 1.17905095, 14.12194248,  2.10889986,  0.20142456],
       [ 0.26084141,  8.88514881,  8.43527622,  1.56182043]])

In [65]:
#EXPONENTES
np.exp(array1)


array([[1.22601067, 1.0552521 , 1.26065266, 1.10504483],
       [2.42011189, 1.76526491, 1.19493201, 1.25233676],
       [1.229319  , 1.66445746, 2.38483925, 1.12579929],
       [1.20720946, 2.63346581, 1.93404349, 2.17001552]])

In [66]:
#seno
np.sin(array1)
np.cos(array2)
np.tan(array3)


array([[  0.23872417,  -3.56620739,   0.38166338,   0.6279155 ],
       [  1.22030442,   1.20695009,   0.22733008,  -6.4081975 ],
       [  2.42074092,  65.67867513,  -1.67544979,   0.20419357],
       [  0.2669227 ,  -0.59892564,  -1.52202299, 111.40644341]])

In [67]:
#logaritmo
np.log(array1)
np.log10(array2)
np.log2(array3)

array([[-2.09333538,  0.88298349, -1.45561472, -0.83471675],
       [-0.17739698, -0.18623442, -2.16145228,  5.05056806],
       [ 0.23762607,  3.81986664,  1.07649059, -2.31168846],
       [-1.93875516,  3.15139594,  3.07643531,  0.64322859]])

COMPARACIONES ENTRE MATRICEZ

In [68]:
#==
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [69]:
# el menor <
array1

array([[0.20376554, 0.0537797 , 0.23162957, 0.0998859 ],
       [0.88381378, 0.56830077, 0.17808929, 0.22501121],
       [0.20646036, 0.50949922, 0.86913172, 0.11849326],
       [0.18831146, 0.96830078, 0.65961288, 0.77473432]])

In [70]:
array1<0.5

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False, False,  True],
       [ True, False, False, False]])

In [71]:
#<= >=
array2

array([[0.86953582, 0.02916177, 0.63529831, 0.17814719],
       [0.99945347, 0.64660698, 0.7967091 , 0.0067894 ],
       [0.17510724, 0.03607855, 0.41212565, 0.58827614],
       [0.72193852, 0.10897969, 0.07819695, 0.49604571]])

In [72]:
array2<=0.6

array([[False,  True, False,  True],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

ESTADISTICAS Y FUNCIONES

In [73]:
array6=np.random.random((5,5))
array6

array([[0.18914548, 0.70248859, 0.62627453, 0.23775301, 0.98718843],
       [0.83524183, 0.63688732, 0.31977413, 0.60886848, 0.69935371],
       [0.95259719, 0.80017913, 0.42365882, 0.10133047, 0.17506866],
       [0.12018   , 0.9273231 , 0.41174651, 0.47078527, 0.58032534],
       [0.55640705, 0.03163654, 0.60956497, 0.51460788, 0.23860103]])

In [74]:
#suma de elementos
sumatotal=np.sum(array6)
sumatotal

np.float64(12.756987484769256)

In [78]:
#valor minimo o maximo
array6.min()
array6.max()


np.float64(0.9871884302647496)

In [79]:
#maximo por fila o columna
array6.max(axis=0)#fila
array6.max(axis=1)#columna

array([0.98718843, 0.83524183, 0.95259719, 0.9273231 , 0.60956497])

In [80]:
#fila acomulada
array6.cumsum(axis=1)

array([[0.18914548, 0.89163407, 1.5179086 , 1.75566162, 2.74285005],
       [0.83524183, 1.47212915, 1.79190328, 2.40077176, 3.10012547],
       [0.95259719, 1.75277632, 2.17643514, 2.27776561, 2.45283427],
       [0.12018   , 1.04750311, 1.45924962, 1.93003489, 2.51036023],
       [0.55640705, 0.58804359, 1.19760856, 1.71221645, 1.95081748]])

In [81]:
#media aritmetica
np.mean(array6)

np.float64(0.5102794993907702)

In [82]:
#mediana
np.median(array6)

np.float64(0.5564070507519421)

In [83]:
#DESVICION ESTANDAR
np.std(array6)

np.float64(0.27441691300899895)